### ISSUE TITLE
Add Tailwind 2 support?

### ISSUE THREAD

**Issue by oller** [neojp/tailwindcss-important-variant#3]
Now that variants can be extended in tailwind 2, as opposed to having to redefine them all again, this plugin appears to have stopped working.

```
    variants: {
        extend: {
            backgroundColor: ["important"],
            borderRadius: ["first", "last"],
            display: ["important"],
            padding: ["important"],
            float: ["important"],
            position: ["important"],
            width: ["important"],
        },
    },
    plugins: [require("@neojp/tailwindcss-important-variant")],
```

It's a very handy plugin!

**Comment by neojp** [comment]
Thanks @oller, I noticed it wasn't working very well in Tailwind v2. There are more css variables involved and I think this accounts for those either. This was mostly a copy & paste from the original documentation for v1, so I'll see what has changed and get that rolled over. It might not happen overnight though, I'm a bit busy at the moment. Thanks for using the plugin!

**Comment by neojp** [comment]
I finally figured out that the function itself is still v2 compatible, but we need to make sure that it is instantiated correctly using the new `plugin()` function.

See their documentation:
https://tailwindcss.com/docs/plugins

```js
// tailwind.config.js
const plugin = require('tailwindcss/plugin');
const importantVariant = require('@neojp/tailwindcss-important-variant');

module.exports = {
  variants: ['important'],
  plugins: [
    plugin(importantVariant)
  ]
};
```
